### ISSUE TITLE
[Routes/Components/Search] Browse Products page

### ISSUE THREAD

**Issue by Taliko5** [IchiBizz/IchiBizz#12]
Backend routes:
- [ ] /api/products

Frontend 
Components:
- [x] Products
    - [x] SearchFilter
    - [x] ProductList

Items:
- [x] Searchbox (search name of the product and also tags of the product)
- [x] Dropdown filter

Filters:
- [x] category
- [x] price
- [x] location
- [x] brand
- [x] tags
- [x] availability

**Comment by ninetteadhikari** [comment]
This issue is completed in the following PRs:
#30 #22 #32 #18 #21 #24
